# -*- coding: utf-8 -*-
"""把彩色轉成單一.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_2fU3nCpEYWyyVwslbmt1VE9HXQNyjk
"""

pip install opencv-python numpy

import cv2
import numpy as np
import os

def convert_to_binary_road(input_path, output_path):
    # 讀取圖片
    img = cv2.imread(input_path)

    # 如果圖片讀取失敗，返回錯誤信息
    if img is None:
        return f"無法讀取圖片: {input_path}"

    # 獲取原始圖片尺寸
    height, width = img.shape[:2]

    # 創建空白圖片(全白)
    binary_img = np.ones((height, width), dtype=np.uint8) * 255

    # 在原始圖片中找到紫色道路的像素
    road_mask = cv2.inRange(img,
                          np.array([100, 0, 100]),
                          np.array([255, 100, 255]))

    # 將道路區域設為黑色(0)
    binary_img[road_mask > 0] = 0

    # 儲存結果
    cv2.imwrite(output_path, binary_img)

    return f"成功處理: {input_path}"

def process_directory(input_dir, output_dir):
    # 確保輸出目錄存在
    os.makedirs(output_dir, exist_ok=True)

    # 支援的圖片格式
    valid_extensions = ('.png', '.jpg', '.jpeg', '.bmp')

    # 計數器
    processed = 0
    failed = 0

    # 處理所有圖片
    for filename in os.listdir(input_dir):
        # 檢查文件副檔名
        if filename.lower().endswith(valid_extensions):
            input_path = os.path.join(input_dir, filename)

            # 生成新的檔案名稱：移除原有副檔名，加上 _labeled.png
            base_name = os.path.splitext(filename)[0]
            output_filename = f"{base_name}_labeled.png"
            output_path = os.path.join(output_dir, output_filename)

            try:
                result = convert_to_binary_road(input_path, output_path)
                print(result)
                processed += 1
            except Exception as e:
                print(f"處理 {filename} 時發生錯誤: {str(e)}")
                failed += 1

    return f"處理完成！成功: {processed} 個文件，失敗: {failed} 個文件"

# 使用範例
input_directory = "/content/1"  # 請替換成你的輸入資料夾路徑
output_directory = "/content/output1"  # 請替換成你想要的輸出資料夾路徑

result = process_directory(input_directory, output_directory)
print(result)

#下載
import shutil

# 定義資料夾路徑和壓縮後的檔案名
folder_path = "/content/output1"
output_filename = "/content/output.zip"

# 壓縮資料夾
shutil.make_archive(output_filename.replace(".zip", ""), 'zip', folder_path)

print(f"{folder_path} 已壓縮為 {output_filename}")

from google.colab import files

# 下載壓縮檔案
files.download(output_filename)